spanish_a1_concepts = [
    "Greetings and Introductions",
    ["Hola", "Buenos días", "Buenas tardes", "Buenas noches", "¿Cómo estás?", "¿Qué tal?", "Me llamo...", "¿Cómo te llamas?", "Mucho gusto"],
    "Numbers",
    ["1-100", "Basic numbers (uno, dos, tres, cuatro, etc.)", "Decades (veinte, treinta, cuarenta...)", "Ordinal numbers (primero, segundo, tercero...)"],
    "Days of the Week",
    ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    "Months",
    ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    "Common Phrases",
    ["¿Qué hora es?", "¿Dónde está?", "¿Cuántos años tienes?", "¿Qué haces?", "¡Hasta luego!"],
    "Common Verbs",
    ["Ser", "Estar", "Tener", "Hacer", "Ir", "Comer", "Beber", "Vivir", "Hablar", "Estudiar"],
    "Basic Adjectives",
    ["Grande", "Pequeño", "Bonito", "Feo", "Bueno", "Malo", "Nuevo", "Viejo", "Fácil", "Difícil"],
    "Nouns and Articles",
    ["Gender: Masculine (el) vs. Feminine (la)", "Singular and plural (libro - libros, mesa - mesas)", "Definite (el, la) vs. indefinite articles (un, una)"],
    "Pronouns",
    ["Personal pronouns: yo (I), tú (you, informal), él/ella (he/she), nosotros/nosotras (we), vosotros/vosotras (you all, informal), ellos/ellas (they)",
     "Possessive pronouns: mi (my), tu (your), su (his/her/its), nuestro/a (our), vuestro/a (your all’s), su (their)"],
    "Present Tense of Regular Verbs",
    ["-AR Verbs: Hablar (yo hablo, tú hablas, él habla, nosotros hablamos, ellos hablan)",
     "-ER Verbs: Comer (yo como, tú comes, él come, nosotros comemos, ellos comen)",
     "-IR Verbs: Vivir (yo vivo, tú vives, él vive, nosotros vivimos, ellos viven)"],
    "Irregular Verbs in the Present Tense",
    ["Ser (yo soy, tú eres, él es, nosotros somos, ellos son)",
     "Estar (yo estoy, tú estás, él está, nosotros estamos, ellos están)",
     "Ir (yo voy, tú vas, él va, nosotros vamos, ellos van)",
     "Tener (yo tengo, tú tienes, él tiene, nosotros tenemos, ellos tienen)"],
    "Adjectives and Agreement",
    ["Adjectives agree in gender and number with nouns", "La casa blanca (The white house)", "Los libros interesantes (The interesting books)"],
    "Simple Questions",
    ["¿Qué?", "¿Quién?", "¿Dónde?", "¿Cuándo?", "¿Cómo?", "¿Por qué?"],
    "Prepositions",
    ["En (in, on)", "A (to, at)", "Con (with)", "Sin (without)", "De (of, from)", "Para (for, to)"],
    "Basic Negation",
    ["No", "Nada", "Nadie", "Nunca"],
    "Basic Sentence Structure",
    ["Subject + verb + object (Yo estudio español)", "Yes/no questions (¿Estudias español?)"],
    "Present Progressive (Present Continuous)",
    ["Formed with the verb 'estar' + gerund (ando/iendo)", "Estoy hablando (I am speaking)", "Estás comiendo (You are eating)"],
    "Family",
    ["Madre", "Padre", "Hermano/a", "Abuelos", "Tío/a"],
    "Food and Drinks",
    ["Pan", "Agua", "Fruta", "Carne", "Vino", "Jugo"],
    "Colors",
    ["Rojo", "Azul", "Verde", "Amarillo", "Blanco", "Negro"],
    "Common Locations",
    ["Casa", "Escuela", "Trabajo", "Tienda", "Restaurante", "Calle"],
    "Time-related Vocabulary",
    ["Hoy", "Mañana", "Ayer", "Ahora", "Siempre", "Nunca"]
]
